#!/bin/bash
export NCCL_SOCKET_IFNAME=eth0
export WANDB_API_KEY="local-9fd3e86800565dfa4b2a5592ccfaf45ef59ec0c6"
# --gradient_accumulation_steps=4 \
# --gradient_checkpointing \
wandb login local-9fd3e86800565dfa4b2a5592ccfaf45ef59ec0c6 --relogin --host=https://microsoft-research.wandb.io
accelerate launch \
    --config_file /home/t2vg-a100-G4-40/code/github/DiT/config/default_config.yaml \
    train_diffusers_imagenet_tardata.py \
    --local-dataset-path ~/datasets/imagenet_feature \
    --vae-path stabilityai/sd-vae-ft-ema \
    --use_ema \
    --resolution 32 \
    --train_batch_size=64 \
    --dataloader_num_workers 1 \
    --num_epochs 1000 \
    --save_model_epochs 40000 \
    --output_dir ~/guangtingsc/t2vg/dit/logs/train_imagenet_256/1015_imagenet_uditdata_testlocal \
    --logger wandb \
    --mixed_precision bf16 \
    --checkpointing_steps 40000 \
    --resume_from_checkpoint latest \
